### ISSUE TITLE
Add support for ipv6 addresses that are wrapped in '[<ipv6]'

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/ipaddr-py#108]
```
What steps will reproduce the problem?

>>> import ipaddr
>>> a = ipaddr.IPAddress('[1::1]')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/google/src/cloud/hines/apes-reserv/google3/third_party/py/ipaddr/__init__.py", line 78, in IPAddress
    address)
ValueError: '[1::1]' does not appear to be an IPv4 or IPv6 address
>>> a = ipaddr.IPAddress('1::1')

What is the expected output? What do you see instead?

should return ipaddr.IPv6Address('1::1')

What version of the product are you using? On what operating system?
>>> ipaddr.__version__
'2.1.10'

Linux

Please provide any additional information below.


```

Original issue reported on code.google.com by `hi...@google.com` on 18 Jun 2014 at 9:46

**Comment by shields** [comment]
Working as intended.  The square brackets are not part of the address.
